reactjs/react-codemod

test/__tests__/transform-tests.js, test/pure-component-test.js, test/pure-component-test.output.js, test/pure-component-test2.js, test/pure-component-test2.output.js, transforms/pure-component.js
This is all I have time for now so I'm throwing it up into a PR.
~~Trying to figure out why Jest won't run.~~
Re: https://twitter.com/cpojer/status/656602748050247680
=> Add pure component transform

README.md, test/__tests__/create-element-to-jsx-test.js, test/create-element-to-jsx-children-literal.js, test/create-element-to-jsx-children-literal.output.js, test/create-element-to-jsx-children.js, test/create-element-to-jsx-children.output.js, test/create-element-to-jsx-no-react.js, test/create-element-to-jsx-props.js, test/create-element-to-jsx-props.output.js, test/create-element-to-jsx-single-element.js, test/create-element-to-jsx-single-element.output.js, test/create-element-to-jsx-spread.js, test/create-element-to-jsx-spread.output.js, transforms/create-element-to-jsx.js
Transforms
```
var a = React.createElement(
Foo,
null,
React.createElement("div", { foo: "bar" }),
React.createElement(
"span",
null,
"blah"
)
);
```
to
```
var a = <Foo><div foo="bar"></div><span>blah</span></Foo>;
```
This codemod is useful for people who start out without using JSX and want to convert their codebase to JSX later.
=> Adding a codemod for transforming createElement function calls to JSX

test/__tests__/create-element-to-jsx-test.js, test/create-element-to-jsx-props-array.js, test/create-element-to-jsx-props-array.output.js, transforms/create-element-to-jsx.js
Converting
```
var foo = React.createElement(
'div',
{
array: []
}
);
```
to
```
var foo = <div array={[]} />;
```
=> create-element-to-jsx-children: Convert non primitive props to JSXExpressionContainer

test/__tests__/create-element-to-jsx-test.js, test/create-element-to-jsx-props-array.js, test/create-element-to-jsx-props-array.output.js, test/create-element-to-jsx-props-boolean.js, test/create-element-to-jsx-props-boolean.output.js, transforms/create-element-to-jsx.js
Based on #11.
Primitive attribute types weren't being wrapped in `{ }`. The only thing that doesn't need to be wrapped in brackets are strings.
=> create-element-to-jsx-children: Convert primitive attribute values properly

test/__tests__/create-element-to-jsx-test.js, test/create-element-to-jsx-children-mixed-empty-string.js, test/create-element-to-jsx-children-mixed-empty-string.output.js, transforms/create-element-to-jsx.js
Based on #10 
This
```
React.createElement(
'div',
null,
a,
' ',
a
);
```
was getting transformed to
```
<div>{a}" "{a}</div>;
```
Now there are no unnecessary quotes.
However, I'm having a problem.
This
```
React.createElement(
'div',
null,
' lala '
);
```
is being converted to
```
<div>lala</div>;
```
Losing the padding spaces. It seems like `j.jsxText('  foo  ');` gets output as `foo`. `literal` has the same issue. So how can I make that case work?
=> create-element-to-jsx-children: Convert mixed strings to JSXText instead of Literal

test/__tests__/create-element-to-jsx-test.js, test/create-element-to-jsx-call-as-children.js, test/create-element-to-jsx-call-as-children.output.js, transforms/create-element-to-jsx.js
The previous code assumed that all children that were of type
CallExpression were in fact calls on MemberExpressions. This fix makes
sure we also support other calls.
=> Allow for a callExpression as child that's not an element.

test/__tests__/create-element-to-jsx-test.js, test/create-element-to-jsx-object-assign.js, test/create-element-to-jsx-object-assign.output.js, test/create-element-to-jsx-react-spread.js, test/create-element-to-jsx-react-spread.output.js, transforms/create-element-to-jsx.js
While reviewing the output of the transform I noticed that the transform lost all attributes for elements that use the `React.__spread` helper. I decided to fix this and make the transform throw an error when it doesn't recognise a certain attribute. This way we can be more sure that things don't fall through.
=> Support React.__spread/Object.assign in JSX transform

test/__tests__/sort-comp-test.js, test/sort-comp-test.js, test/sort-comp-test.output.js, transforms/sort-comp.js, transforms/utils/ReactUtils.js
Reorders React component methods to match the [ESLint](http://eslint.org/) [react/sort-comp rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md), specifically with the [tighter constraints of the Airbnb style guide](https://github.com/airbnb/javascript/blob/6c89f9587f96688bf0d4d536adb8eb4ed9bf0002/packages/eslint-config-airbnb/rules/react.js#L47-L57):
```
'react/sort-comp': [2, {
'order': [
'lifecycle',
'/^on.+$/',
'/^(get|set)(?!(InitialState$|DefaultProps$|ChildContext$)).+$/',
'everything-else',
'/^render.+$/',
'render'
]
}],
```
NOTE: only works on React.createClass() syntax, not ES6 class.
=> add sort-comp transform into compliance with eslint react/sort-comp

test/__tests__/create-element-to-jsx-test.js, test/create-element-to-jsx-gt-lt-entities.js, test/create-element-to-jsx-gt-lt-entities.output.js, transforms/create-element-to-jsx.js
Previously the transform would translate
```
React.createElement("div", null, "\x3C");
```
To
```
<div><</div>;
```
This PR fixes this by translating `<>` to `&lt;&gt;`.
=> Make sure less-than and great-than characters are properly encoded.

test/__tests__/sort-comp-test.js, test/sort-comp-test2.js, test/sort-comp-test2.output.js, transforms/sort-comp.js, transforms/utils/ReactUtils.js
In a comment in sort-comp, I noticed the following comment:
> NOTE: only works on React.createClass() syntax, not ES6 class.
I thought that it would be really lovely if this worked with ES6
classes, so I decided to take a crack at adding support.
Fixes #27
=> Add support for ES6 classes in sort-comp

test/create-element-to-jsx-allow-member-expression.js
When running tests locally, I noticed that eslint warned here. Using
single quotes satisfies the linter in this case.
=> Fix linter warning in a test file

README.md, test/sort-comp-test2.js, test/sort-comp-test2.output.js, transforms/sort-comp.js
The Airbnb JavaScript style guide was recently updated to sort static
methods to the tops of classes [0]. Since this codemod is designed to
follow the constraints of the Airbnb style guide, I figured it would be
good to update this as well.
[0]: https://github.com/airbnb/javascript/pull/715
=> Teach sort-comp to put static methods at the top

transforms/sort-comp.js
I noticed some extra loop iteration in #31 so did a little refactoring.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/reactjs/react-codemod/32)
=> simplify getRefPropIndexes() logic

test/sort-comp-test2.js, test/sort-comp-test2.output.js, transforms/sort-comp.js
Also simplifies the logic. I originally based it off https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/sort-comp.js, but it doesn't need to be nearly as complex because it doesn't have to give useful error output.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/reactjs/react-codemod/33)
=> take method ordering in sort-comp as an option

README.md
Signature according to https://github.com/facebook/jscodeshift#usage-cli is actually `<path>`.
=> Update the README to follow jscodeshift doc

transforms/__testfixtures__/create-element-to-jsx-no-props-arg.input.js, transforms/__testfixtures__/create-element-to-jsx-no-props-arg.output.js, transforms/__tests__/create-element-to-jsx-test.js, transforms/create-element-to-jsx.js
`React.createElement(Component)`, without the second `props` argument,
was failing with `TypeError: Cannot read property 'type' of undefined`
error. As `React.createElement()` allows emitting the `props` argument
altogether as far as I have understood, the codemod shouldn't fail when
props argument is indeed missing.
=> Fix create-element-to-jsx failing when props argument is missing

README.md
Tried running the sort-comp without npm installing first and got 
```
ERR /client/scripts/myFile.js Transformation error
Error: Cannot find module 'eslint'
at Function.Module._resolveFilename (module.js:440:15)
at Function.Module._load (module.js:388:25)
at Module.require (module.js:468:17)
at require (internal/module.js:20:19)
at getMethodsOrderFromEslint (/tmp/react-codemod/transforms/sort-comp.js:179:21)
at getMethodsOrder (/tmp/react-codemod/transforms/sort-comp.js:194:8)
at module.exports (/tmp/react-codemod/transforms/sort-comp.js:39:24)
```
=> Add "npm install" to readme

transforms/sort-comp.js
The current file actually sorts the methods in the wrong order in Node 6.2.0.
=> Dont put regexes in quotes

transforms/__testfixtures__/pure-component.input.js, transforms/__testfixtures__/pure-component.output.js, transforms/pure-component.js
This fixes #56, skips over components that render with a `ref`.
=> 56: identify components with refs as impure

README.md
As mentioned in #59, the `create-element-to-jsx` codemod can destroy comments,
so leave a warning in the docs so people know to be careful.
Also add a "Support and Contributing" section at the bottom of the README that
briefly describes the state and purpose of the repo and how contributions are
handled.
=> Document bug in create-element-to-jsx, add Contributing section

README.md, transforms/__testfixtures__/create-element-to-jsx-preserve-comments.input.js, transforms/__testfixtures__/create-element-to-jsx-preserve-comments.output.js, transforms/__tests__/create-element-to-jsx-test.js, transforms/create-element-to-jsx.js
Originally filed as #59.
Some non-obvious aspects of this change:
* For the main test, I put a comment between nearly every token. The generated
output is really messy, but the main important thing is that every comment in
the input appears somewhere in the output.
* For closing tags, I had to make a copy of the JSXIdentifier without any
comments. Otherwise, `React.createElement('div' /*foo*/, null, ' ')` would
become `<div /*foo*/> </div /*foo*/>`.
* I had to change the signature of `convertExpressionToJSXAttributes` to also
return an `extraComments` value for any comments that didn't have an obvious
attribute to attach to. This is also necessary since there might be no
attributes, but still some comments.
* JSXText elements seem to ignore any comments you attach to them, so I had to …
=> Make create-element-to-jsx properly transfer comments

transforms/sort-comp.js
This fixes the issue where react/sort-comp eslint rules such as `"/^render+.$/"` are incorrectly converted to `/\/^render.+$\//` rather than `/^render.+$/`
=> sort-comp instantiates regex from eslintrc properly

transforms/class.js
`toString() {}` was getting converted to `static toString = () => {}`. JavaScript.
=> Bug fixes from running class transform at Facebook

transforms/__testfixtures__/manual-bind-to-arrow/manual-bind-to-arrow1.input.js, transforms/__testfixtures__/manual-bind-to-arrow/manual-bind-to-arrow1.output.js, transforms/__testfixtures__/manual-bind-to-arrow/manual-bind-to-arrow2.input.js, transforms/__testfixtures__/manual-bind-to-arrow/manual-bind-to-arrow2.output.js, transforms/__testfixtures__/manual-bind-to-arrow/manual-bind-to-arrow3.input.js, transforms/__testfixtures__/manual-bind-to-arrow/manual-bind-to-arrow4.input.js, transforms/__testfixtures__/manual-bind-to-arrow/manual-bind-to-arrow4.output.js, transforms/__testfixtures__/manual-bind-to-arrow/manual-bind-to-arrow5.input.js, transforms/__testfixtures__/manual-bind-to-arrow/manual-bind-to-arrow5.output.js, transforms/__testfixtures__/manual-bind-to-arrow/manual-bind-to-arrow6.input.js, transforms/__testfixtures__/manual-bind-to-arrow/manual-bind-to-arrow6.output.js, transforms/__testfixtures__/manual-bind-to-arrow/manual-bind-to-arrow7.input.js, transforms/__testfixtures__/manual-bind-to-arrow/manual-bind-to-arrow7.output.js, transforms/__testfixtures__/manual-bind-to-arrow/manual-bind-to-arrow8.input.js, transforms/__testfixtures__/manual-bind-to-arrow/manual-bind-to-arrow8.output.js, transforms/__tests__/manual-bind-to-arrow-test.js, transforms/manual-bind-to-arrow.js
This converts the manual bind to an arrow property initializer function.
It works for the base case `this.method = this.method.bind(this);`, two other patterns that I've seen in the codebase that should be codemodded as well in a subsequent version
- `(this: any).method = this.method.bind(this)`
- `const self = (this: any); self.method = this.method.bind(this)`
Test Plan:
npm t
I haven't tried it on the codebase yet, just want to get early feedback
=> Initial version of manual bind to arrow function

README.md
Hey reactjs team,
I came to the manual-bind-to-arrow transform following a tweet from Sebastian. I ran it and it worked fantastically on my project. So I took a moment to add some brief documentation to the README. 
Any feedback would be welcome.
=> Add documentation for manual-bind-to-arrow

transforms/__testfixtures__/create-element-to-jsx-ignore-bad-capitalization.input.js, transforms/__testfixtures__/create-element-to-jsx-ignore-bad-capitalization.output.js, transforms/__tests__/create-element-to-jsx-test.js, transforms/create-element-to-jsx.js
JSX uses capitalization to determine what type of `React.createElement` call to
produce: if the name starts with a lower-case letter, `React.createElement` is
called with the name as a string. Otherwise, it is called with the name as an
identifier. This means that an expression like `React.createElement(componentClass)`
cannot be converted to JSX, since `<componentClass />` would transform to the
string form. This commit changes the script to detect and skip these cases so
that the script does not introduce correctness issues.
=> Skip incorrectly-capitalized cases in create-element-to-jsx

transforms/__testfixtures__/create-element-to-jsx-ignore-bad-capitalization.input.js, transforms/__testfixtures__/create-element-to-jsx-ignore-bad-capitalization.output.js, transforms/create-element-to-jsx.js
In #79, I made it so the transformation is skipped in some cases, in particular
when the capitalization is invalid. This broke an assumption elsewhere in the
code that `convertNodeToJSX` always returns a `JSXElement`, so there was a crash
if a skipped element was used as a child. To fix, we can just wrap in a
`JSXExpressionContainer` for that case.
=> Fix crash due to skipped children in create-element-to-jsx

transforms/__testfixtures__/create-element-to-jsx-arg-spread.input.js, transforms/__testfixtures__/create-element-to-jsx-arg-spread.output.js, transforms/__tests__/create-element-to-jsx-test.js, transforms/create-element-to-jsx.js
The default case for child nodes is to wrap them in `JSXExpressionContainer`
nodes, but that doesn't work when a spread arg is given as a child. Spread args
in `React.createElement` are actually unnecessary (and probably bad practice)
because React can handle an array given as a child. So to fix, I just got the
underlying value from the spread (generally an array) and use that as the child.
Note that this could potentially introduce key warnings because React now sees
an actual array, but those warnings are probably good.
=> Fix crash in create-element-to-jsx when using spread args

transforms/__testfixtures__/create-element-to-jsx-escaped-string.input.js, transforms/__testfixtures__/create-element-to-jsx-escaped-string.output.js, transforms/__tests__/create-element-to-jsx-test.js, transforms/create-element-to-jsx.js
JSX prop value strings are treated more like HTML strings than JavaScript
strings, so things like escape sequences don't work: it just uses a literal
backslash character. Also, if the string contains a `"` character, recast will
generate a double-quoted string with the `"` characters escaped, which isn't
valid for JSX prop strings. To fix, we wrap the string in curly braces if it
directly uses an escape sequence (i.e. the underlying code has a backslash) or
if it has a `"` character.
=> Fix incorrect prop value strings in create-element-to-jsx

transforms/__testfixtures__/pure-component.input.js, transforms/__testfixtures__/pure-component.output.js, transforms/__testfixtures__/pure-component2.input.js, transforms/__testfixtures__/pure-component2.output.js, transforms/pure-component.js
I was going to split this into a few PRs, but they're kinda related.
Firstly, it now treats any Component with a `ClassProperty` which isn't `props` as being impure.
Secondly, it retains any static `ClassProperty`s.
Finally, it retains `props` type annotations when transforming to a function.
I haven't used jscodeshift before, so happy to make any changes if there's a cleaner way of accomplishing it :)
``` js
// input
class PureWithTypes extends React.Component {
props: { foo: string };
render() {
return <div className={this.props.foo} />;
}
}
// output
const PureWithTypes = (props: { foo: string }) => {
return <div className={props.foo} />;
}
```
=> pure-component: support Type Annotations & Class Properties

transforms/__testfixtures__/create-element-to-jsx-computed-component.input.js, transforms/__testfixtures__/create-element-to-jsx-computed-component.output.js, transforms/__tests__/create-element-to-jsx-test.js, transforms/create-element-to-jsx.js
The create-element-to-jsx script was almost always calling `jsxIdentifierFor`,
which assumed that the expression consisted of strings, identifiers, and
non-computed member expressions (i.e. dot syntax rather than brackets syntax).
This ended up crashing or causing incorrect output when run on more dynamic code
like `React.createElement(a[b])`, `React.createElement(a[b.c])`, and
`React.createElement(f())`.
=> Skip computed component values in create-element-to-jsx

transforms/__testfixtures__/create-element-to-jsx-allow-member-expression.output.js, transforms/__testfixtures__/create-element-to-jsx-arg-spread.output.js, transforms/__testfixtures__/create-element-to-jsx-call-as-children.output.js, transforms/__testfixtures__/create-element-to-jsx-call-expression-as-prop.output.js, transforms/__testfixtures__/create-element-to-jsx-children-literal.output.js, transforms/__testfixtures__/create-element-to-jsx-children-map.output.js, transforms/__testfixtures__/create-element-to-jsx-children-mixed-empty-string.output.js, transforms/__testfixtures__/create-element-to-jsx-children.output.js, transforms/__testfixtures__/create-element-to-jsx-deep-nesting.input.js, transforms/__testfixtures__/create-element-to-jsx-deep-nesting.output.js, transforms/__testfixtures__/create-element-to-jsx-gt-lt-entities.output.js, transforms/__testfixtures__/create-element-to-jsx-ignore-bad-capitalization.output.js, transforms/__testfixtures__/create-element-to-jsx-literal-spacing.input.js, transforms/__testfixtures__/create-element-to-jsx-literal-spacing.output.js, transforms/__testfixtures__/create-element-to-jsx-member-expression-as-prop.output.js, transforms/__testfixtures__/create-element-to-jsx-preserve-comments.output.js, transforms/__tests__/create-element-to-jsx-test.js, transforms/create-element-to-jsx.js
See https://github.com/benjamn/recast/issues/365 for more context.
It looks like the recast printer includes all JSX on the same line by default,
which can lead to really ugly code with deeply nested React elements. However,
if we put a `'\n'` text node around all adjacent children, it will format the
JSX in the typical multiline way, properly indented, so this commit changes the
script to do that.
Ideally, we might want to keep some expressions inline, e.g. by determining
whether the child expressions will fit nicely on one line, but that seems sort
of nontrivial with just the AST, so we just use multiline JSX always for now.
To keep strings correct, we need to be a little more careful about translating
child string literals. Since each child will be on its own line, leading and
trailing …
=> Format JSX children across multiple lines in create-element-to-jsx

package.json, transforms/__testfixtures__/create-element-to-jsx-element-comment-positioning.input.js, transforms/__testfixtures__/create-element-to-jsx-element-comment-positioning.output.js, transforms/__testfixtures__/create-element-to-jsx-preserve-comments.output.js, transforms/__tests__/create-element-to-jsx-test.js, transforms/create-element-to-jsx.js, yarn.lock
Previously, this code:
```js
React.createElement(
Foo, // This is a comment
{bar: baz}
);
```
would change to this code:
```js
<// This is a comment
Foo bar={baz} />
```
This is technically correct, but really ugly, so this commit changes the script
to reposition the comment to be on the outer JSXElement instead of the
JSXIdentifier directly. As we traverse the first arg to `React.createElement`,
we collect all comments and add them to the array of comments that we'll
eventually add to the outer JSXElement.
Note that this depends on a fix to recast that was just released in version
0.11.22. See this PR for more details: https://github.com/benjamn/recast/pull/364
Without that change, the repositioned comment could sometimes cause the
resulting code to be incorrect if it's at the start of …
=> Don't put comments on JSXIdentifier nodes in create-element-to-jsx

transforms/ReactNative-View-propTypes.js, transforms/__testfixtures__/ReactNative-View-propTypes/default-import-multi-reference.input.js, transforms/__testfixtures__/ReactNative-View-propTypes/default-import-multi-reference.output.js, transforms/__testfixtures__/ReactNative-View-propTypes/default-import-only-reference.input.js, transforms/__testfixtures__/ReactNative-View-propTypes/default-import-only-reference.output.js, transforms/__testfixtures__/ReactNative-View-propTypes/default-require-multi-reference.input.js, transforms/__testfixtures__/ReactNative-View-propTypes/default-require-multi-reference.output.js, transforms/__testfixtures__/ReactNative-View-propTypes/default-require-only-reference.input.js, transforms/__testfixtures__/ReactNative-View-propTypes/default-require-only-reference.output.js, transforms/__testfixtures__/ReactNative-View-propTypes/destructured-import-multi-reference.input.js, transforms/__testfixtures__/ReactNative-View-propTypes/destructured-import-multi-reference.output.js, transforms/__testfixtures__/ReactNative-View-propTypes/destructured-import-only-reference.input.js, transforms/__testfixtures__/ReactNative-View-propTypes/destructured-import-only-reference.output.js, transforms/__testfixtures__/ReactNative-View-propTypes/destructured-require-multi-reference.input.js, transforms/__testfixtures__/ReactNative-View-propTypes/destructured-require-multi-reference.output.js, transforms/__testfixtures__/ReactNative-View-propTypes/destructured-require-only-reference.input.js, transforms/__testfixtures__/ReactNative-View-propTypes/destructured-require-only-reference.output.js, transforms/__testfixtures__/ReactNative-View-propTypes/import-flow-type-with-require.input.js, transforms/__testfixtures__/ReactNative-View-propTypes/import-flow-type-with-require.output.js, transforms/__testfixtures__/ReactNative-View-propTypes/multiple-replacements.input.js, transforms/__testfixtures__/ReactNative-View-propTypes/multiple-replacements.output.js, transforms/__testfixtures__/ReactNative-View-propTypes/noop-import.input.js, transforms/__testfixtures__/ReactNative-View-propTypes/noop-require.input.js, transforms/__tests__/ReactNative-View-propTypes-test.js
`ReactNative` will soon be deprecating `View.propTypes` in favor of `ViewPropTypes`. This codemod helps with that deprecation by doing the following:
* Updates all references to `View.propTypes` and replaces them with `ViewPropTypes`.
* Adds an `import` or `require` statement (depending on the convention followed in the parent file) for the new `ViewPropTypes`.
* Removes the `import`/`require` statement for `View` if it is no longer in use.
* Uses Haste modules (eg `import ViewPropTypes from 'ViewPropTypes';`) if it detects their use in the file else uses Node modules (eg `import { ViewPropTypes } from 'react-native';`).
In addition to the newly added Jest tests this codemod was also run internally against Facebook's `ReactNative` code.
This codemod may introduce an unnecessary newline …
=> Migrate ReactNative View.propTypes to ViewPropTypes

README.md, transforms/__testfixtures__/class/class-initial-state.output.js, transforms/__testfixtures__/class/class-prune-react.input.js, transforms/__testfixtures__/class/class-prune-react.output.js, transforms/__testfixtures__/class/class-prune-react2.input.js, transforms/__testfixtures__/class/class-prune-react2.output.js, transforms/__testfixtures__/class/class-prune-react3.input.js, transforms/__testfixtures__/class/class-prune-react3.output.js, transforms/__testfixtures__/class/class-pure-mixin3.input.js, transforms/__testfixtures__/class/class-pure-mixin3.output.js, transforms/__testfixtures__/class/class-test2.output.js, transforms/__testfixtures__/class/class.output.js, transforms/__tests__/class-test.js, transforms/class.js
If React.createClass cannot be converted to a plain JavaScript class,
it falls back to using the react-create-class package instead.
=> Update class transform to fallback to react-create-class package

transforms/React-propTypes-to-prop-types.js, transforms/__testfixtures__/React-propTypes-to-prop-types/default-and-named-import.input.js, transforms/__testfixtures__/React-propTypes-to-prop-types/default-and-named-import.output.js, transforms/__testfixtures__/React-propTypes-to-prop-types/default-import.input.js, transforms/__testfixtures__/React-propTypes-to-prop-types/default-import.output.js, transforms/__testfixtures__/React-propTypes-to-prop-types/no-change-import.input.js, transforms/__testfixtures__/React-propTypes-to-prop-types/no-change-require.input.js, transforms/__testfixtures__/React-propTypes-to-prop-types/require-destructured-multi.input.js, transforms/__testfixtures__/React-propTypes-to-prop-types/require-destructured-multi.output.js, transforms/__testfixtures__/React-propTypes-to-prop-types/require-destructured-only.input.js, transforms/__testfixtures__/React-propTypes-to-prop-types/require-destructured-only.output.js, transforms/__testfixtures__/React-propTypes-to-prop-types/require.input.js, transforms/__testfixtures__/React-propTypes-to-prop-types/require.output.js, transforms/__tests__/React-propTypes-to-prop-types-test.js
This goes with the upcoming React 15.5 release.
This codemod may introduce an unnecessary newline before certain types of imports. This is not a problem with the codemod but with recast. See facebook/jscodeshift/issues/185 and benjamn/recast/issues/371
=> Replace React.propTypes with PropTypes from prop-types

transforms/React-PropTypes-to-prop-types.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/named-import.input.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/named-import.output.js, transforms/__tests__/React-PropTypes-to-prop-types-test.js
When creating reusable shapes it one only need proptypes and might
therefore not have imported react. This change make the proptype codemod
handle this use case.
Output of the added test before the change:
```js
import 'react';
export default PropTypes.shape({
id: PropTypes.string,
})
```
Output of the added test after the change:
```js
import PropTypes from 'prop-types';
export default PropTypes.shape({
id: PropTypes.string,
})
```
=> Fix issue with only named import of proptypes

transforms/React-PropTypes-to-prop-types.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/assigned-from-react-var.input.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/assigned-from-react-var.output.js, transforms/__tests__/React-PropTypes-to-prop-types-test.js
Previously the codemod might transform:
```js
const PropTypes = React.PropTypes;
```
To:
```js
const PropTypes = PropTypes;
```
I've now added handling for this (and tests)
=> Added more edge-case handling to PropTypes codemod

transforms/React-DOM-to-react-dom-factories.js, transforms/__testfixtures__/React-DOM-to-react-dom-factories/react-dom-basic-case.input.js, transforms/__testfixtures__/React-DOM-to-react-dom-factories/react-dom-basic-case.output.js, transforms/__testfixtures__/React-DOM-to-react-dom-factories/react-dom-deconstructed-import.input.js, transforms/__testfixtures__/React-DOM-to-react-dom-factories/react-dom-deconstructed-import.output.js, transforms/__testfixtures__/React-DOM-to-react-dom-factories/react-dom-deconstructed-require-part-two.input.js, transforms/__testfixtures__/React-DOM-to-react-dom-factories/react-dom-deconstructed-require-part-two.output.js, transforms/__testfixtures__/React-DOM-to-react-dom-factories/react-dom-deconstructed-require.input.js, transforms/__testfixtures__/React-DOM-to-react-dom-factories/react-dom-deconstructed-require.output.js, transforms/__testfixtures__/React-DOM-to-react-dom-factories/react-dom-no-change-dom-from-other-libraries.input.js, transforms/__testfixtures__/React-DOM-to-react-dom-factories/react-dom-no-change-import.input.js, transforms/__testfixtures__/React-DOM-to-react-dom-factories/react-dom-no-change-require.input.js, transforms/__tests__/React-DOM-to-react-dom-factories-test.js
Since we are deprecating the 'React.DOM.*' factories,(https://github.com/facebook/react/issues/9398 and https://github.com/facebook/react/pull/8356) we want to
provide a codemod so that it's easier for folks to upgrade their code.
This will include an option to use 'React.createFactory' instead of
'React.createElement' in case there is a use case where that is
preferred.
There is one use of `React.DOM.*` that I have seen which is not covered
here - sometimes it has mistakenly been used for Flow typing. In the
cases I have found it is not proper syntax and doesn't seem like
something we should cover with this codemod.
=> Add codemod for 'React.DOM.div' -> 'React.createElement("div"'

transforms/React-PropTypes-to-prop-types.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/nested-destructured-proptypes-import.input.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/nested-destructured-proptypes-import.output.js, transforms/__tests__/React-PropTypes-to-prop-types-test.js
Fixes #134 but not in a totally ideal way.
=> Add handling for nested destructuring

transforms/React-PropTypes-to-prop-types.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/require-destructured-direct.input.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/require-destructured-direct.output.js, transforms/__tests__/React-PropTypes-to-prop-types-test.js
I was using React-PropTypes-to-prop-types to convert files in our repo,
and I noticed that this type of construct wouldn't be converted:
const { PropTypes } = require('react');
To fix this, I modified a function that handled constructs of the
following kind:
const { PropTypes } = React;
Naming the test fixture was a little hard, since there are other
fixtures testing almost the same thing. I decided to use the term
"direct" to refer to a destructure done "directly" aimed at a require.
=> Fix React-PropTypes-to-prop-types for destructured require

README.md
**what is the change?:**
`npm` -> `yarn`
**why make this change?:**
I personally find it confusing to have 'npm' in the docs when I'm trying
to use 'yarn' consistently.
**test plan:**
Visual inspection
=> Use 'yarn' in main README

transforms/React-PropTypes-to-prop-types.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/assigned-to-var-with-different-name.input.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/assigned-to-var-with-different-name.output.js, transforms/__tests__/React-PropTypes-to-prop-types-test.js
While running this codemod against some FB source I discovered a case that wasn't handled correctly:
```js
const React = require('react');
const ReactPropTypes = React.PropTypes;
const string = ReactPropTypes.string;
```
Would get incorrectly converted to:
```js
const React = require('react');
// ReactPropTypes is not defined
const string = ReactPropTypes.string;
```
This PR contains a fix as well as an added test case. Now the codemod only removes pointers that have names that conflict with the import, eg:
```js
const React = require('react');
const ReactPropTypes = React.PropTypes;
const string = ReactPropTypes.string;
```
Will now be converted to:
```js
const PropTypes = require('prop-types');
const React = require('react');
const ReactPropTypes = PropTypes;
const string = …
```
=> Fixed PropTypes codemod bug that left invalid variable references

transforms/React-PropTypes-to-prop-types.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/already-migrated-import.input.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/already-migrated-import.output.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/already-migrated-require.input.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/already-migrated-require.output.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/import-flow-type-with-require.input.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/import-flow-type-with-require.output.js, transforms/__tests__/React-PropTypes-to-prop-types-test.js
This PR fixes 2 problems observed while running against Facebook code:
* Avoids adding duplicate `prop-types` imports/requires if they already exist. (eg maybe the codemod was already run and then a regression slipped in.)
* Make sure `import type` doesn't give false-positives when it comes to determining whether a given file uses `import` or `require` syntax.
Tests added for both fixes.
=> Edge-case fixes for PropTypes codemod

transforms/class.js
This trailing comma was causing the class transform to fail on my environment even when called with the `--babel` flag.
Environment info:
- macOS 10.12.2
- jscodeshift: v0.3.30
- babel and friends: v6.24.1
=> Remove trailing function comma in class transform

transforms/__testfixtures__/class/class-initial-state.input.js, transforms/__testfixtures__/class/class-initial-state.output.js, transforms/class.js
Howdy!
This change adds support for when `getInitialState` is defined with arrow functions. I've also added the corresponding test cases. 
Please let me know if I missed anything! 
Supported cases:
```javascript
// ArrowFunctionExpression with BlockStatement body
React.createClass({
getInitialState: (): {heyoo: number} => {
return {
heyoo: 23,
};
},
});
// ArrowFunctionExpression with ObjectExpression body
React.createClass({
getInitialState: (): {heyoo: number} => ({
heyoo: 23,
}),
});
```
=> Support transforming getInitialState defined via arrow functions

transforms/__testfixtures__/class/class-pure-mixin5.input.js, transforms/__testfixtures__/class/class-pure-mixin5.output.js, transforms/__tests__/class-test.js, transforms/class.js
As is, the class transformation will indiscriminately delete the declaration when removing the PureMixin dependency.
With this change, it will only delete the declaration if the mixin import was the only declarator for the import declaration.
I've gone ahead and added a corresponding test case.
=> Class transform - Preserve the import declaration when deleting pure mixin import if necessary

README.md
context https://github.com/facebook/jscodeshift/issues/172 : if not using this option, any file that uses `*` flow type syntax will fail.
=> mention the --parser=flow option in the README doc

transforms/__testfixtures__/class/class-prune-react4.input.js, transforms/__testfixtures__/class/class-prune-react4.output.js, transforms/__tests__/class-test.js, transforms/class.js
When replacing `React.createClass` with  `createReactClass`, the React import was being erroneously deleted even though JSX existed in the file.
This change ensures that the React import is not erroneously removed. Added a corresponding test case.
=> Class transform - Remove React import only if it should be removed

transforms/React-PropTypes-to-prop-types.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/with-top-comment.input.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/with-top-comment.output.js, transforms/__tests__/React-PropTypes-to-prop-types-test.js
As shown in #147, if the React import is preceded by a comment, the `prop-types` import is printed before it, and not after. This is especially problematic when using the `// @flow` pragma, since it won't be a the top of the file anymore, and therefore won't work. This PR fixes this problem, using the [recipe advised by jscodeshift](https://github.com/facebook/jscodeshift/blob/master/recipes/retain-first-comment.md). However, I do have a whitespace problem, that I can't succeed to fix.
```javascript
/**
* This is some multiline comment
*/
import React, { PropTypes } from 'react';
// gets converted to 
/**
* This is some multiline comment
*/
import PropTypes from 'prop-types';
import React from 'react';
```
If someone knows how to fix that, I'll update the PR ASAP. If not, I still do think …
=> Retain leading comment fix #147

README.md, transforms/__testfixtures__/rename-unsafe-lifecycles/arrow-functions.input.js, transforms/__testfixtures__/rename-unsafe-lifecycles/arrow-functions.output.js, transforms/__testfixtures__/rename-unsafe-lifecycles/create-react-class.input.js, transforms/__testfixtures__/rename-unsafe-lifecycles/create-react-class.output.js, transforms/__testfixtures__/rename-unsafe-lifecycles/instance-methods.input.js, transforms/__testfixtures__/rename-unsafe-lifecycles/instance-methods.output.js, transforms/__testfixtures__/rename-unsafe-lifecycles/standalone-function.input.js, transforms/__testfixtures__/rename-unsafe-lifecycles/variable-within-class-method.input.js, transforms/__tests__/rename-unsafe-lifecycles-test.js, transforms/rename-unsafe-lifecycles.js
This codemod corresponds with reactjs/rfcs/pull/6 and facebook/react/pull/12028
This codemod was tested in the React repo by running:
```sh
jscodeshift \
-t ../react-codemod/transforms/rename-unsafe-lifecycles.js \
--parser=flow \
./packages/**/src/**/*.js
```
I also ran this codemod internally on `fbsource` and it seemed to work okay, except for a single parse error (before the transform was applied).
=> Add rename-unsafe-lifecycles codemod

transforms/__testfixtures__/rename-unsafe-lifecycles/manually-calling-lifecycles.input.js, transforms/__testfixtures__/rename-unsafe-lifecycles/manually-calling-lifecycles.output.js, transforms/__testfixtures__/rename-unsafe-lifecycles/one-lifecycle-calls-another.input.js, transforms/__testfixtures__/rename-unsafe-lifecycles/one-lifecycle-calls-another.output.js, transforms/__tests__/rename-unsafe-lifecycles-test.js, transforms/rename-unsafe-lifecycles.js
When running this codemod internally I found several places where lifecycles are being invoked manually, either as part of a test or from other lifecycles. I have added a couple of additional tests and updated the codemod to cover this.
=> Rename lifecycle invocations too

transforms/__testfixtures__/rename-unsafe-lifecycles/manually-invoked-mixin-methods.input.js, transforms/__testfixtures__/rename-unsafe-lifecycles/manually-invoked-mixin-methods.output.js, transforms/__tests__/rename-unsafe-lifecycles-test.js, transforms/rename-unsafe-lifecycles.js
Follow-up to #198
When running this codemod internally I found several additional places manually invoking lifecycles like `SomeComponent.componentDidMount.apply()` so the codemod has been updated to handle this case also.
So I've changed the codemod from renaming `CallExpression`s (eg `instance.method()`) to broader `MemberExpression`s (eg `instance.method()` _and_ `instance.method.apply()`).
Additional tests have been added.
=> More broadly rename MemberExpressions

README.md, bin/react-codemod.js, package.json
An improvement to actually using these codemods. You should be able to `npx react-codemod <transform> path/to/src` and it should Just Work™️. Also updates the docs to prefer this version.
Did it as a quick hack so I could show during the meeting, happy to work on it further if it looks good. Would be good to point to in 16.9.0 release notes as well.
=> POC - npx react-codemod <transform> <path/to/src>

bin/cli.js
`React-PropTypes-to-prop-types` was missing in the `TRANSFORMER_INQUIRER_CHOICES` list. This commit fixes that. 
Fixes #230
=> fix: add missing transformer option React-PropTypes-to-prop-types

transforms/class.js
This is a fix for #123. Potentially this could be made more generic by checking `path.parentPath.value.type` and check if it's CallExpression or something else, but in order to avoid potential false positives I decided to just make the fix for this specific case.
Comments welcome! This issue was preventing us from converting some of our classes, and I would be happy if this issue could be resolved and potentially help others.
=> Do not consider history.replaceState() deprecated

transforms/React-PropTypes-to-prop-types.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/already-migrated-named-as-import.input.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/already-migrated-named-as-import.output.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/already-migrated-named-import.input.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/already-migrated-named-import.output.js, transforms/__tests__/React-PropTypes-to-prop-types-test.js
Fixes `React-PropTypes-to-prop-types` codemod transforming already migrated named imports incorrectly.
These:
```js
import { PropTypes } from 'prop-types';
```
```js
import { PropTypes as PT } from 'prop-types';
```
Were incorrectly transformed into this:
```js
import 'prop-types';
```
This PR adds a check to transform only nodes importing from `react`, thus ignoring those importing from `prop-types`.
Previously this codemod would basically assume already migrated stuff to use default export:
```js
import PropTypes from 'prop-types';
```
Also adds tests for both cases.
Fixes #187
=> React-PropTypes-to-prop-types: ignore migrated named import

transforms/React-DOM-to-react-dom-factories.js, transforms/React-PropTypes-to-prop-types.js, transforms/ReactNative-View-propTypes.js, transforms/create-element-to-jsx.js, transforms/manual-bind-to-arrow.js, transforms/react-to-react-dom.js
The documentation makes reference to the ability to pass `--printOptions`, but this is not strictly observed in all transforms. Since these transformations can potentially affect hundreds of files, it might be annoying to not be able to change recast's defaults, like when it replaces all line-feeds with `CRLF` on Windows.
I tried to honor the existing format in each file with this PR. Since some conventions are not uniform among the existing transformations, I did not use the same format everywhere. Please let me know if you would like for me to adjust this PR as necessary.
I think it is worth noting that it may also be prudent to use something like `Object.assign` and merge the CLI and transform options, rather than just using the CLI options OR the transform's defaults.
=> Consistently use printOptions

transforms/sort-comp.js
This PR supports the `type-annotations` group described in https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md
=> Support the `type-annotations` group in sort-comp.

transforms/utils/ReactUtils.js
Hi guys.
I was implementing a `sort-comp` fixer in the project when noticed that PureComponent is always skipped. This happens because `findReactES6ClassDeclarationByParent` searches only for occurrences of a `Component` even if a `PureComponent` was passed.
=> Fix forgotten PureComponent in ReactUtils

README.md, bin/__tests__/react-codemod-test.js, bin/cli.js
thanks to ismusidhu in https://github.com/reactjs/react-codemod/pull/205/
=> adds back the explicit-require option

transforms/rename-unsafe-lifecycles.js
Thanks to @skovy in https://github.com/reactjs/react-codemod/pull/228, we have a fix for this codemod not working correctly for typescript files. Making this a separate commit/PR to unblock publishing.
=> support typescript in rename-unsafe-lifecycles

transforms/__testfixtures__/rename-unsafe-lifecycles/typescript/class.tsx.input.js, transforms/__testfixtures__/rename-unsafe-lifecycles/typescript/class.tsx.output.js, transforms/__tests__/rename-unsafe-lifecycles-test.js
Only the tests from https://github.com/reactjs/react-codemod/pull/228.
The transform has to be mocked because `jscodeshift` doesn't support testing other parsers/file extensions.
I named the examples `class.tsx.input.js` (must be `js` to match what `jscodeshift` expects) but still keep the `tsx` to help show that it's expected to actually be a TSX file (and can be if something like https://github.com/facebook/jscodeshift/pull/332 is merged). Happy to remove this and keep it only `class.input.js` 😕
=> Add TypeScript tests for the rename-unsafe-lifecycles transform

bin/__tests__/react-codemod-test.js, bin/cli.js
It seems common enough that we should allow it. Also folks use .js with typescript sometimes.
=> adds --extensions=jsx,js by default

transforms/__testfixtures__/custom-sort-group/.eslintrc, transforms/__testfixtures__/custom-sort-group/custom-sort-group.input.js, transforms/__testfixtures__/custom-sort-group/custom-sort-group.output.js, transforms/__tests__/custom-sort-group.js, transforms/sort-comp.js
Picking the logic from https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/sort-comp.js#L59 to support groups with order. Airbnb style guide also uses groups and react-codemod doesn't sort methods properly when defined using them.
=> Add support for handling groups for method ordering in sort-comp codemod

transforms/__testfixtures__/manual-bind-to-arrow/manual-bind-to-arrow10.input.js, transforms/__testfixtures__/manual-bind-to-arrow/manual-bind-to-arrow10.output.js, transforms/__testfixtures__/manual-bind-to-arrow/manual-bind-to-arrow9.input.js, transforms/__testfixtures__/manual-bind-to-arrow/manual-bind-to-arrow9.output.js, transforms/__tests__/manual-bind-to-arrow-test.js, transforms/manual-bind-to-arrow.js
- Created a test with two components declared and bound functions with different names. This passes.
- Created a test with two components declared and bound functions with same name. This fails.
Added fix to scope the method/constructor removal to the corresponding component declaration instead of the root of the file.
=> Issues/181 : manual-bind-to-arrow does not clean up constructor binds when the same bind occurs multiple times

package.json
This should fix the sort-comp code-mod as stated in #51
=> Fixes #51: Declare eslint dependency

transforms/__testfixtures__/pure-component.input.js, transforms/__testfixtures__/pure-component.output.js, transforms/__testfixtures__/pure-component2.input.js, transforms/__testfixtures__/pure-component2.output.js, transforms/pure-component.js, transforms/utils/ReactUtils.js
**case 1: Default exported classes**
When converting a class combined with a default export, to a pure component, you end up creating a syntax error. This is because you cannot combine the default keyword with a lexical declaration. This PR separates the declaration from the export in this case. 
**case 2: Unused super class import remains**
When converting to a pure functional component the old super class may have a named import that is no longer used. This should be removed.
**case 3: Props argument exists even if its never used**
=> Fix pure component transform edge cases

transforms/__testfixtures__/update-react-imports/react-type-default-export.input.js, transforms/__testfixtures__/update-react-imports/react-type-default-export.output.js, transforms/__tests__/update-react-imports-test.js, transforms/update-react-imports.js
Sometimes, `jscodeshift` will modify files that it touched even though the codemod may not have actually modified any code. Because `jscodeshift` sometimes doesn't play well with types, this sometimes leads to files being modified unintentionally in strange ways. This PR adds an early return if we know we aren't going to modify any react imports in `update-react-imports` to avoid these unintentional modifications.
This PR also fixes a bug where we treat `import type React from 'react'` the same as `import React from 'react'`.
=> Update update-react-imports with early return

README.md, bin/cli.js, transforms/__testfixtures__/update-react-imports/flow-default-and-type-specifier-import-react-variable.output.js, transforms/__testfixtures__/update-react-imports/react-already-used-named-export.input.js, transforms/__testfixtures__/update-react-imports/react-basic-default-export-jsx-element-react-variable.output.js, transforms/__testfixtures__/update-react-imports/react-basic-default-export.output.js, transforms/__testfixtures__/update-react-imports/react-jsx-member-expression.input.js, transforms/__testfixtures__/update-react-imports/react-jsx-member-expression.output.js, transforms/__testfixtures__/update-react-imports/react-not-removed.input.js, transforms/__testfixtures__/update-react-imports/react-not-removed.output.js, transforms/__testfixtures__/update-react-imports/react-type-not-removed.input.js, transforms/__testfixtures__/update-react-imports/react-type-not-removed.output.js, transforms/__testfixtures__/update-react-imports/variable-already-used.input.js, transforms/__tests__/update-react-imports-test.js, transforms/update-react-imports.js
This PR updates the `update-react-imports` codemod. Previously, this codemod removed unused React imports (as a result of the new JSX transform) and converted default imports to named imports. This PR goes a step further and destructures those named imports (ex. `import {useState} from 'react'` if they were previously default imports. Named React imports (`import * as React from 'react'`) are untouched
=> update-react-imports: Destructure named exports

README.md, bin/cli.js, transforms/__testfixtures__/update-react-imports/destructure-named-imports-react-not-removed.input.js, transforms/__testfixtures__/update-react-imports/destructure-named-imports-variable-used.input.js, transforms/__testfixtures__/update-react-imports/destructure-named-imports.input.js, transforms/__testfixtures__/update-react-imports/destructure-named-imports.output.js, transforms/__tests__/update-react-imports-test.js, transforms/update-react-imports.js
We originally did not destructure named imports because it was pointed out to us that some people might want to keep the `import * as React from 'react'` option. However, [this issue](https://github.com/reactjs/react-codemod/issues/277) points out that there are codebases that would prefer to use destructured named imports (ex. `import {useState} from 'react'`) instead now that React no longer needs to be in scope to use JSX. This PR introduces an option to the transform that allows people to choose to destructure named imports as well as default imports.
=> Add Destructure Named Imports Option for `update-react-imports`
