test/__tests__/create-element-to-jsx-test.js, test/create-element-to-jsx-spread-props.js, test/create-element-to-jsx-spread-props.output.js, transforms/create-element-to-jsx.js
=> Handling props as a spread attribute

test/__tests__/create-element-to-jsx-test.js, test/create-element-to-jsx-allow-member-expression.js, test/create-element-to-jsx-allow-member-expression.output.js, transforms/create-element-to-jsx.js
Tests should cover why I would like to have this.
=> Allow for MemberExpression in JSXIdentifier

transforms/create-element-to-jsx.js
=> [Create-Element-To-JSX] support for --no-explicit-react

transforms/findDOMNode.js
This PR adds the support for ES6 exports in the findDOMNode transform.
=> Account for exports.

transforms/__testfixtures__/sort-comp3.input.js, transforms/__testfixtures__/sort-comp3.output.js, transforms/__tests__/create-element-to-jsx-test.js, transforms/utils/ReactUtils.js
Update `hasReact` check to include `react-native`.  This allows usage without the --explicit-require=false option.
=> add react-native support

README.md
now observes eslintconfig
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/reactjs/react-codemod/49)
=> Update sort-comp doc for #48

transforms/sort-comp.js
adds try...catch around reading of eslintrc in sort-comp
=> 51: handle failure to read eslint config options for file

.eslintrc, .eslintrc.js, package.json, transforms/__testfixtures__/.eslintrc, transforms/__testfixtures__/class.input.js, transforms/__testfixtures__/class.output.js, transforms/create-element-to-jsx.js, transforms/utils/ReactUtils.js
=> Upgrade eslint and jest

transforms/__testfixtures__/class-initial-state.output.js, transforms/class.js
Reviewers: @spicyj 
Test Plan:
- It parses and works correctly (tested)
cc @samwgoldman
=> annotate unannotated non-liftable state with ExistsType

jest/env.js, package.json
=> Upgrade jest to 15.1.1

transforms/pure-component.js
see more at https://github.com/reactjs/react-codemod/issues/64
=> Prevented throwing exception in 'pure-component' transform

transforms/__testfixtures__/react-to-react-dom/import-dom-base.input.js, transforms/__testfixtures__/react-to-react-dom/import-dom-base.output.js, transforms/__testfixtures__/react-to-react-dom/import-multiple-specifiers.input.js, transforms/__testfixtures__/react-to-react-dom/import-multiple-specifiers.output.js, transforms/__testfixtures__/react-to-react-dom/import-server-base.input.js, transforms/__testfixtures__/react-to-react-dom/import-server-base.output.js, transforms/__testfixtures__/react-to-react-dom/import-with-existing-react-dom.input.js, transforms/__testfixtures__/react-to-react-dom/import-with-existing-react-dom.output.js, transforms/__testfixtures__/react-to-react-dom/import-without-default-specifier.input.js, transforms/__testfixtures__/react-to-react-dom/import-without-default-specifier.output.js, transforms/__testfixtures__/react-to-react-dom/mixed-with-existing-react-dom.input.js, transforms/__testfixtures__/react-to-react-dom/mixed-with-existing-react-dom.output.js, transforms/__testfixtures__/react-to-react-dom/require-dom-base.input.js, transforms/__testfixtures__/react-to-react-dom/require-dom-base.output.js, transforms/__testfixtures__/react-to-react-dom/require-indirect.input.js, transforms/__testfixtures__/react-to-react-dom/require-indirect.output.js, transforms/__testfixtures__/react-to-react-dom/require-keeps-react.input.js, transforms/__testfixtures__/react-to-react-dom/require-keeps-react.output.js, transforms/__testfixtures__/react-to-react-dom/require-server-base.input.js, transforms/__testfixtures__/react-to-react-dom/require-server-base.output.js, transforms/__tests__/react-to-react-dom-test.js, transforms/react-to-react-dom.js
=> Add es6 support to react-to-react-dom transform

package.json, transforms/__testfixtures__/class/class-create-class-naming.output.js, transforms/__testfixtures__/class/class-displayName.input.js, transforms/__testfixtures__/class/class-displayName.output.js, transforms/__testfixtures__/class/class-initial-state.input.js, transforms/__testfixtures__/class/class-initial-state.output.js, transforms/__testfixtures__/class/class-prune-react.output.js, transforms/__testfixtures__/class/class-prune-react2.output.js, transforms/__testfixtures__/class/class-prune-react3.output.js, transforms/__testfixtures__/class/class-pure-mixin3.output.js, transforms/__testfixtures__/class/class-test2.output.js, transforms/__testfixtures__/class/class.output.js, transforms/__tests__/class-test.js, transforms/class.js, yarn.lock
Based on the transform-react-display-name Babel transform.
=> Update the createClass transform to insert a display name

transforms/React-PropTypes-to-prop-types.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/default-and-named-import.output.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/default-import.input.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/default-import.output.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/no-change-import.input.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/no-change-require.input.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/require-destructured-multi.output.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/require-destructured-only.input.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/require-destructured-only.output.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/require.output.js
=> PropTypes transform respects alphasort when inserting import/require

transforms/React-PropTypes-to-prop-types.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/default-import.input.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/default-import.output.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/named-parameters.input.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/named-parameters.output.js, transforms/__tests__/React-PropTypes-to-prop-types-test.js
=> Additional edge-case handling for named parameters

transforms/React-PropTypes-to-prop-types.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/mixed-import-and-require.input.js, transforms/__testfixtures__/React-PropTypes-to-prop-types/mixed-import-and-require.output.js, transforms/__tests__/React-PropTypes-to-prop-types-test.js
=> Handle mixed imports and requires

README.md
Unordered list mean, that every item of list is optional.
=> Replace unordered list to ordered

.eslintignore, transforms/React-PropTypes-to-prop-types.js, transforms/ReactNative-View-propTypes.js, transforms/__tests__/error-boundaries.js, transforms/__tests__/react-to-react-dom-test.js, transforms/create-element-to-jsx.js, transforms/error-boundaries.js, transforms/react-to-react-dom.js, transforms/sort-comp.js
- Fix ESLint Warnings
- Add `__testfixtures__` to `.eslintignore`
=> Fix ESLint Warnings & Add .eslintignore

transforms/utils/ReactUtils.js
https://github.com/reactjs/react-codemod/issues/139
=> Adds PureComponent support to ReactUtils

bin/react-codemod.js
As per https://github.com/facebook/jscodeshift/issues/307.
Documentation of this argument on `jscodeshift` here: https://github.com/facebook/jscodeshift#usage-cli
=> --ignore-pattern expects a glob pattern

README.md, bin/cli.js
fixes https://github.com/reactjs/react-codemod/issues/192
=> add React-DOM-to-react-dom-factories to cli/readme

bin/cli.js
=> Add --explicit-require to CLI help command

package.json, yarn.lock
See https://github.com/reactjs/react-codemod/issues/306
=> Fix all codemods by pinning version of colors.js
